/// <reference lib="webworker" />
import { clientsClaim } from 'workbox-core';
import { precacheAndRoute } from 'workbox-precaching';

// Required for vite-plugin-pwa injectManifest
self.skipWaiting();
clientsClaim();

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST || []);

// Listen for Push Events
self.addEventListener('push', (event) => {
  let data = {};
  if (event.data) {
    try {
      data = event.data.json();
    } catch (e) {
      data = { title: event.data.text() };
    }
  }

  const title = data.title || 'Incoming Video Call';
  const options = {
    body: data.body || 'Someone is calling you. Tap to answer.',
    icon: '/favicon.svg',
    badge: '/favicon.svg',
    // Aggressive ringing pattern: vibrate for 500ms, pause for 200ms, repeat
    vibrate: [500, 200, 500, 200, 500, 200, 500, 200, 500, 200, 500, 200, 500], 
    data: {
      url: data.url || '/'
    },
    requireInteraction: true, // Keep notification open until the user clicks it
    actions: [
      { action: 'answer', title: 'Answer Call' },
      { action: 'decline', title: 'Decline' }
    ]
  };

  event.waitUntil(
    self.registration.showNotification(title, options)
  );
});

self.addEventListener('notificationclick', (event) => {
  event.notification.close();

  if (event.action === 'decline') {
    return;
  }

  const urlToOpen = new URL(event.notification.data.url, self.location.origin).href;

  event.waitUntil(
    self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((windowClients) => {
      // Check if there is already a window/tab open with the target URL
      for (let i = 0; i < windowClients.length; i++) {
        const client = windowClients[i];
        if (client.url === urlToOpen && 'focus' in client) {
          return client.focus();
        }
      }
      // If not, then open the target URL in a new window/tab.
      if (self.clients.openWindow) {
        return self.clients.openWindow(urlToOpen);
      }
    })
  );
});
