/// <reference lib="webworker" />
import { clientsClaim } from 'workbox-core';
import { precacheAndRoute } from 'workbox-precaching';

// Required for vite-plugin-pwa injectManifest
self.skipWaiting();
clientsClaim();

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST || []);

// Listen for Push Events
self.addEventListener('push', (event) => {
  let data = {};
  if (event.data) {
    try {
      data = event.data.json();
    } catch (e) {
      data = { title: event.data.text() };
    }
  }

  const title = data.title || 'Incoming Video Call';
  const options = {
    body: data.body || 'Someone is calling you. Tap to answer.',
    icon: '/favicon.svg',
    badge: '/favicon.svg',
    // Aggressive ringing pattern: vibrate for 500ms, pause for 200ms, repeat
    vibrate: [500, 200, 500, 200, 500, 200, 500, 200, 500, 200, 500, 200, 500], 
    data: {
      url: data.url || '/'
    },
    requireInteraction: true, // Keep notification open until the user clicks it
    actions: [
      { action: 'answer', title: 'Answer Call' },
      { action: 'decline', title: 'Decline' }
    ]
  };

  event.waitUntil(
    self.registration.showNotification(title, options)
  );
});

self.addEventListener('notificationclick', (event) => {
  event.notification.close();

  if (event.action === 'decline') {
    return;
  }

  const targetPath = event.notification.data.url || '/';
  const urlToOpen = new URL(targetPath, self.location.origin).href;

  event.waitUntil(
    self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((windowClients) => {
      // Find any open tab of our app
      const appClient = windowClients.find(client => client.url.startsWith(self.location.origin));
      
      if (appClient) {
        // If an app tab is open, focus it and tell React to route there instantly
        appClient.focus();
        appClient.postMessage({ type: 'NAVIGATE', url: targetPath });
        return;
      }
      
      // If the app is fully closed, open a new window
      if (self.clients.openWindow) {
        return self.clients.openWindow(urlToOpen);
      }
    })
  );
});
