/// <reference lib="webworker" />
import { clientsClaim } from 'workbox-core';
import { precacheAndRoute } from 'workbox-precaching';

// Required for vite-plugin-pwa injectManifest
self.skipWaiting();
clientsClaim();

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST || []);

// Listen for Push Events
self.addEventListener('push', (event) => {
  let data = {};
  if (event.data) {
    try {
      data = event.data.json();
    } catch (e) {
      data = { title: event.data.text() };
    }
  }

  // Handle Cancel Event
  if (data.type === 'cancel' && data.roomId) {
    event.waitUntil(
      self.registration.getNotifications({ tag: data.roomId }).then((notifications) => {
        notifications.forEach(notification => notification.close());
      })
    );
    // Also notify any open app to stop the in-app ringing
    event.waitUntil(
      self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((windowClients) => {
        const appClient = windowClients.find(client => client.url.startsWith(self.location.origin));
        if (appClient) {
          appClient.postMessage({ type: 'CANCEL_CALL', roomId: data.roomId });
        }
      })
    );
    return; 
  }

  const title = data.title || 'Incoming Video Call';
  const urlPath = data.url || '/';
  const roomId = data.roomId || (urlPath.includes('/room/') ? urlPath.split('/').pop() : 'default-call');

  event.waitUntil(
    self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((windowClients) => {
      const visibleAppClient = windowClients.find(client => 
        client.url.startsWith(self.location.origin) && client.visibilityState === 'visible'
      );
      
      if (visibleAppClient) {
        // App is open and visible! Tell the React app to show the in-app modal instead of a system notification
        visibleAppClient.postMessage({ type: 'INCOMING_CALL', data: { title, url: urlPath, roomId, body: data.body } });
        return;
      }

      const isMobile = /Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent);
      
      // App is closed, show system notification
      const options = {
        body: data.body || 'Someone is calling you. Tap to answer.',
        icon: '/favicon.svg',
        badge: '/favicon.svg',
        tag: roomId, // Tag allows us to close it remotely if canceled
        vibrate: [500, 200, 500, 200, 500, 200, 500, 200, 500, 200, 500, 200, 500], 
        data: {
          url: urlPath,
          roomId
        },
        requireInteraction: true,
        actions: isMobile ? [] : [
          { action: 'answer', title: 'Answer Call' },
          { action: 'decline', title: 'Decline' }
        ]
      };

      return self.registration.showNotification(title, options);
    })
  );
});

self.addEventListener('notificationclick', (event) => {
  event.notification.close();

  if (event.action === 'decline') {
    return;
  }

  const targetPath = (event.notification.data && event.notification.data.url) ? event.notification.data.url : '/';
  const urlToOpen = new URL(targetPath, self.location.origin).href;

  const handleNavigation = async () => {
    // If they explicitly clicked the 'Answer' button, some Android devices block focus().
    // We will aggressively try to open the window or focus it.
    const windowClients = await self.clients.matchAll({ type: 'window', includeUncontrolled: true });
    const appClient = windowClients.find(client => client.url.startsWith(self.location.origin));

    if (appClient) {
      appClient.postMessage({ type: 'NAVIGATE', url: targetPath });
      try {
        await appClient.focus();
      } catch (e) {
        // Fallback if focus is blocked by Android for action buttons
        if (event.action === 'answer' && self.clients.openWindow) {
           await self.clients.openWindow(urlToOpen);
        }
      }
    } else {
      if (self.clients.openWindow) {
        await self.clients.openWindow(urlToOpen);
      }
    }
  };

  event.waitUntil(handleNavigation());
});
